version: 2.1

jobs:
  build:
    machine: true
    working_directory: ~/save-link-trello
    steps:
      - checkout
      - run:
          name: Installing Heroku cli
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Build Docker image
          command: docker build -t gnimish/save-link-trello:$CIRCLE_SHA1 . --build-arg ENVIRONMENT=production
      - run:
          name: Push to Docker hub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push gnimish/save-link-trello:$CIRCLE_SHA1
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker tag gnimish/save-link-trello:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            heroku container:release web -a $HEROKU_APP_NAME

workflows:
  build:
    jobs:
      - build
